# Use root/example as user/password credentials
version: '3.1'

services:
  rbac-api-dev:
    build:
      context: .
      target: develop
    command: npm run start:dev
    container_name: rbac-api-dev
    environment:
      - NODE_ENV=develop
    ports:
      - '3000:3000'
    restart: always
    networks:
      - app-network
    depends_on:
      - db
      - cache
      - elasticsearch
      - kibana

  rbac-api-prod:
    build:
      context: .
      target: production
    container_name: rbac-api-prod
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    restart: always
    networks:
      - app-network
    depends_on:
      - db
      - cache
      - elasticsearch
      - kibana

  db:
    #platform: linux/amd64
    #    hostname: mysql
    container_name: demo-db
    # build: ./docker/mysql
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysql
      # - ./mysql:/var/run/mysqld
    command: 'mysqld --innodb-flush-method=fsync --innodb-use-native-aio=0'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - app-network

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - app-network

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - app-network
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 1000M

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 1000M

volumes:
  mysqldb:
  es-data:
  cache:
    driver: local

networks:
  app-network:
    driver: bridge
